### ISSUE TITLE
InvalidHeaderValue (400): The value for one of the HTTP headers is not in the correct format

### ISSUE THREAD

**Issue by elsesiy** [Azure/azure-storage-ruby#164] opened 2020-04-27 18:32 UTC
Hi, I'm using this plugin in the context of [fluentd with managed identity authentication](https://github.com/microsoft/fluent-plugin-azure-storage-append-blob/pull/9).

This worked fine until recently without any modifications but now the logs are flooded with the following error:
```
#0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-04-27 18:26:44 +0000 chunk="5a3d1ea5814dd2c1fd37f7364311cd23" error_class=Azure::Core::Http::HTTPError error="InvalidHeaderValue (400): The value for one of the HTTP headers is not in the correct format.\nRequestId:b67c7175-c01e-0010-4ac1-1c5d33000000\nTime:2020-04-27T18:26:43.7364703Z"
  2020-04-27 18:26:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/azure-storage-common-2.0.1/lib/azure/core/http/http_request.rb:153:in `call'
  2020-04-27 18:26:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/azure-storage-common-2.0.1/lib/azure/core/http/signer_filter.rb:28:in `call'
  2020-04-27 18:26:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/azure-storage-common-2.0.1/lib/azure/core/http/signer_filter.rb:28:in `call'
  2020-04-27 18:26:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/azure-storage-common-2.0.1/lib/azure/core/http/http_request.rb:110:in `block in with_filter'
  2020-04-27 18:26:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/azure-storage-common-2.0.1/lib/azure/core/service.rb:36:in `call'
  2020-04-27 18:26:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/azure-storage-common-2.0.1/lib/azure/core/filtered_service.rb:34:in `call'
  2020-04-27 18:26:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/azure-storage-common-2.0.1/lib/azure/core/signed_service.rb:41:in `call'
  2020-04-27 18:26:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/azure-storage-common-2.0.1/lib/azure/storage/common/service/storage_service.rb:60:in `call'
```

Any idea what's going on?

**Comment by elsesiy** [comment] 2020-04-28 17:25
@katmsft This issue is causing a vast amount of requests not going through and seems to happen arbitrarily with both `1.1.0` and `2.0.0`. Some requests are going through and other are not, so I have no idea about the semantics of the headers set on the requests. Can you help out here? Thanks!

**Comment by elsesiy** [comment] 2020-04-29 20:19
According to the microsoft support the `append_blob_block` operation is failing because the `Content-Length` header is not correctly populated. Looking at the most [recent documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/append-block#request-headers) for this operation, the header is required but it's not set in the [code](https://github.com/Azure/azure-storage-ruby/blob/0d3e5acf3327652fa2ffe1ed1df73b61a5a17c1e/blob/lib/azure/storage/blob/append.rb#L150).

This explains why the first operation of creating the blob doesn't fail but appending to it does. To me this sounds like the server version was upgraded and now requires this header to be present

**Comment by katmsft** [comment] 2020-04-30 02:27
I don't think the final comment is valid. Although the content length is not set from where you linked, but it is set [here](https://github.com/Azure/azure-storage-ruby/blob/e5059568b6b971f6981b454fd71cf211429d418e/common/lib/azure/core/http/http_request.rb#L168) if the request body is not null. With this said, if the request failed because the content length is not set, it must be the content itself is null.
To ensure that this is the case, can you provide a recent repro (within a day or even better within several hours) for me to take a look at the server log?

**Comment by elsesiy** [comment] 2020-04-30 05:27
@katmsft I can't create a recent repro because it works fine again now. Can't you look at the request id in the issue description or maybe even search through the server logs for said storage account? Thank you!

**Comment by elsesiy** [comment] 2020-04-30 17:02
I don't see any errors anymore but logs just stop being uploaded after a while. I'm not very familiar with Ruby but maybe there's something wrong with [this](https://github.com/Azure/azure-storage-ruby/tree/master/blob#access-token) snippet that is used [here](https://github.com/microsoft/fluent-plugin-azure-storage-append-blob/pull/9/files#diff-6bfc3b4a26ee1dae42e548451a41110aR98)?

**Comment by katmsft** [comment] 2020-05-01 07:39
As I mentioned, the request's detailed log is already rolled over. We would like to help but there isn't really much that can be done since it cannot be reproduced anymore.
We will close this issue but feel free to reopen or create other issues when you encounter the failure again.

**Comment by elsesiy** [comment] 2020-05-01 19:03
@katmsft I'm now experiencing issues with the aforementioned code snippet for getting/refreshing a MSI token:
```
2020-05-01 18:55:20 +0000 [warn]: #0 failed to flush the buffer. retry_time=10 next_retry_seconds=2020-05-01 19:04:26 +0000 chunk="5a38cef28bfe80d5693848449c94c6eb" error_class=Azure::Core::Http::HTTPError error="AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:4faacf66-701e-0048-33ea-1f3996000000\nTime:2020-05-01T18:55:20.4181830Z"
```

The pod identity is assigned and the token refresh succeeds
```
time="2020-05-01T18:25:55Z" level=info msg="matched identityType:0 clientid:5968##### REDACTED #####6f4b resource:https://storage.azure.com/" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.4.0.45
```

The initial token issued has a validity of `expires-in: 86339` so about 24 hours but apparently the blob storage client that gets the underlying token credential refreshed can't authenticate after the expiration of the initial token anymore.

How can I ensure the blob storage client is using the new credential when talking to the storage api?

**Comment by katmsft** [comment] 2020-05-07 01:11
You would need to set up a timer in your code to call [`renew_token`](https://github.com/Azure/azure-storage-ruby/blob/master/common/lib/azure/storage/common/core/token_credential.rb#L58) API every ~24 hours. This needs to be done prior to the token being expired so it is your choice how long in advance of 24 hours you want to refresh it.

BTW, please open new issues for additional questions/issues, and keep one issue discussing one topic on the SDK. Thanks!

**Comment by elsesiy** [comment] 2020-05-07 02:11
@katmsft That's what I'm doing already using the method described in the readme. Please klick on the links to examine the snippets mentioned [here]https://github.com/Azure/azure-storage-ruby/issues/164#issuecomment-621980554.

**Comment by katmsft** [comment] 2020-05-07 03:02
Then I don't understand why the token cannot be authenticated, the code snippet should work.
Some checks that you might want to do to narrow it down:
1. Although the token has a validity of 24 hours, please leave some buffer before the refresh period to ensure the token is updated.
2.  Please check the headers that get sent, and verify that the token is successfully updated.

**Comment by elsesiy** [comment] 2020-05-07 05:27
@katmsft That’s exactly why I’m reporting this because I don’t understand why this is happening either.

I did both of the things with a refresh interval of 50 minutes, logged the token and made sure the token is successfully refreshed (just like in the example).
That being said, I don’t think refreshing the token as advertised in the README works and that’s what should be investigated.

**Comment by katmsft** [comment] 2020-05-11 02:54
To further investigate the issue, it needs to be identified whether the problem is that the SDK failed to update the token or the token refreshed is not valid.
Please use the debug filter to print out the token that fails the request and see if the token is successfully updated using the code snippet.
Alternatively, you can email the token to me and the exact time of the token being used, then I can check if the token's expiry time.

The debug filter can be used with any client using following line of code:
```
service.with_filter Azure::Core::Http::DebugFilter.new
```

Thanks for your patience.

**Comment by katmsft** [comment] 2020-05-11 03:05
Please remove the signature in the token before you send it with an email, which is the part from the last comma to the end of the token.

**Comment by elsesiy** [comment] 2020-05-13 04:09
@katmsft As I said, the token refreshed is valid and I established that by printing the token during each refresh and looking at the jwt claims. The SDK just doesn't seem to pick it up properly. Unfortunately I don't have any capacity to further investigate this issue and due to MSI limitations (no cross-tenant access), we won't be using this for now. Nonetheless I think it makes sense to investigate this and creating a repro shouldn't be too hard.

Thanks!

**Comment by vinjiang** [comment] 2020-07-14 08:50
Please let us know if you need further assistance on this issue.

**Closed by vinjiang** 2020-07-14 08:50 UTC
