### ISSUE TITLE
Can't upload files with extra spaces in name

### ISSUE THREAD

**Issue by alagos** [Azure/azure-storage-ruby#127] opened 2018-08-21 17:49 UTC
I was having a problem trying to upload a specific file:
```
Exception: Azure::Core::Http::HTTPError: AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:6c56b513-d01e-000f-4573-39b4f5000000
Time:2018-08-21T17:22:58.4131119Z
--
 0: /home/alter/.rvm/gems/ruby-2.4.2@productwatcher/gems/azure-core-0.1.14/lib/azure/core/http/http_request.rb:153:in `call'
 1: /home/alter/.rvm/gems/ruby-2.4.2@productwatcher/gems/azure-core-0.1.14/lib/azure/core/http/signer_filter.rb:28:in `call'
 2: /home/alter/.rvm/gems/ruby-2.4.2@productwatcher/gems/azure-core-0.1.14/lib/azure/core/http/signer_filter.rb:28:in `call'
 3: /home/alter/.rvm/gems/ruby-2.4.2@productwatcher/gems/azure-core-0.1.14/lib/azure/core/http/http_request.rb:110:in `block in with_filter'
 4: /home/alter/.rvm/gems/ruby-2.4.2@productwatcher/gems/azure-core-0.1.14/lib/azure/core/service.rb:36:in `call'
 5: /home/alter/.rvm/gems/ruby-2.4.2@productwatcher/gems/azure-core-0.1.14/lib/azure/core/filtered_service.rb:34:in `call'
 6: /home/alter/.rvm/gems/ruby-2.4.2@productwatcher/gems/azure-core-0.1.14/lib/azure/core/signed_service.rb:41:in `call'
 7: /home/alter/.rvm/gems/ruby-2.4.2@productwatcher/gems/azure-storage-common-1.0.1/lib/azure/storage/common/service/storage_service.rb:60:in `call'
 8: /home/alter/.rvm/gems/ruby-2.4.2@productwatcher/gems/azure-storage-blob-1.0.1/lib/azure/storage/blob/blob_service.rb:176:in `call'
 9: /home/alter/.rvm/gems/ruby-2.4.2@productwatcher/gems/azure-storage-blob-1.0.1/lib/azure/storage/blob/block.rb:416:in `create_block_blob_single_put'
10: /home/alter/.rvm/gems/ruby-2.4.2@productwatcher/gems/azure-storage-blob-1.0.1/lib/azure/storage/blob/block.rb:111:in `create_block_blob'
```

Debugging deeper to see what was the sent header (date may vary according to exception):
```ruby
{"User-Agent"=>"Azure-Storage/1.0.1-1.0.1 (Ruby 2.4.2-p198; Linux linux-gnu)",
 "x-ms-date"=>"Tue, 21 Aug 2018 16:56:13 GMT",
 "x-ms-version"=>"2016-05-31",
 "DataServiceVersion"=>"1.0;NetFx",
 "MaxDataServiceVersion"=>"3.0;NetFx",
 "Content-Type"=>"application/atom+xml; charset=utf-8",
 "x-ms-blob-type"=>"BlockBlob",
 "x-ms-meta-name"=>"atril  hernan videla.jpg",
 "x-ms-meta-model_class"=>"Attachment",
 "x-ms-meta-model_attachment"=>"file",
 "x-ms-blob-content-type"=>"application/octet-stream",
 "Content-Length"=>"3377852",
 "Content-MD5"=>"q8n/AnLjwN0yDth1s5loPA==",
 "Authorization"=>"my_private_key"}
```
I checked that in 
```
"x-ms-meta-name"=>"atril  hernan videla.jpg"
```
, the filename has more than one space. Then I tried with `atril hernan videla.jpg` (without two spaces in name) and it worked. Then, just to confirm, I tried with 
```
"atril    videla.jpg"
```
(4 spaces) and it failed again. 
To me looks like a bug, because it never happened me before until this file name, but maybe I'm wrong.

**Comment by rlb3** [comment] 2018-08-27 14:25
I also see this bug with files that have spaces in the file name.

**Comment by yaxia** [comment] 2018-09-28 02:57
Thanks for reporting the issue. We will look into it.

**Comment by yaxia** [comment] 2018-11-19 03:40
This is caused by an issue in the azure-core. Sent a [PR #64](https://github.com/Azure/azure-ruby-asm-core/pull/64) to fix.

**Comment by yaxia** [comment] 2018-12-03 03:52
@rlb3 I cannot reproduce your issue where the spaces are in the file name. Because the file name is in the request URL and the spaces will be encoded to %20. My fix won't change the behavior of handling URL.
Can you share what the exact request that you have issue?

**Comment by rlb3** [comment] 2018-12-03 04:53
Thank you for taking a look but I'm no longer at that company and no longer have access the code.

**Comment by yaxia** [comment] 2018-12-03 06:54
@rlb3 Thanks for the update. I will close this issue since the issue of the spaces in the metadata is fixed.

**Comment by yaxia** [comment] 2018-12-10 09:02
@alagos please get the latest release of azure-core (0.1.15) for the fix. Thanks.

**Closed** 2018-12-10 12:14 UTC
Labels: bug
