### ISSUE TITLE
copy_blob_from_uri should raise the response as an exception if response does not contain 'x-ms-copy-id' nor 'x-ms-copy-status'

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-storage-ruby#40] opened 2016-08-18 07:00 UTC
copy_blob_from_uri should raise the response as an exception if response does not contain 'x-ms-copy-id' nor 'x-ms-copy-status'.
One of our customer has failed in copy_blob_from_uri but could not get any useful information because the caller got ['',''] as the result.

```
    def copy_blob_from_uri(destination_container, destination_blob, source_blob_uri, options={})
      ...
      response = call(:put, uri, nil, headers)
      return response.headers['x-ms-copy-id'], response.headers['x-ms-copy-status']
    end
```

copy_blob_from_uri

**Comment by yaxia** [comment] 2016-08-18 07:36
I will take a look.

**Comment by yaxia** [comment] 2016-08-23 07:09
Throwing an exception is an easy change, but I think it is not the root cause. From the [Storage REST API](https://msdn.microsoft.com/en-us/library/azure/dd894037.aspx), the copy operation should always return the `x-ms-copy-id` and the `x-ms-copy-status` headers if the request succeeds.

Could you please provide more details such as reproduce steps or reproduce rate, then I can investigate for the root cause?

**Comment by AbelHu** [comment] 2016-08-24 02:48
No more logs from azure_storage_ruby. It is difficult to repro.
```
I, [2016-08-15T19:04:38.069750 #35722]  INFO -- : Copy id: , copy status:
E, [2016-08-15T19:04:38.069867 #35722] ERROR -- : Failed to copy the blob https://yemenstorageaccount.blob.core.windows.net/stemcell/bosh-stemcell-b7159bf4-0609-44ad-a043-7232b10b8207.vhd:
           copy status:
           copy description:
```

**Comment by AbelHu** [comment] 2016-09-05 03:32
@yaxia Do you have any progress on this? I think SDK should handle exception if the server does not return correct values, how do you think? Otherwise, we have to handle it by ourselves.

**Comment by yaxia** [comment] 2016-09-06 02:32
The SDK does throw exception when there is error in the response. You can see from the [HttpRequest](https://github.com/Azure/azure-ruby-asm-core/blob/master/lib/azure/core/http/http_request.rb#L147) and [RetryPolicy](https://github.com/Azure/azure-ruby-asm-core/blob/master/lib/azure/core/http/retry_policy.rb#L46).
The root cause is in somewhere else. It is not a good practice to raise exception by validating the headers again when the server returns successfully, unless we prove there is a serer issue. I will keep looking.

**Comment by AbelHu** [comment] 2016-09-06 06:29
I agree with you that normally SDK should follow the REST API doc to implement it. But now there is a bug in the REST API. If SDK does not raise an exception including headers, the caller cannot get any useful information. For trouble shooting, I think SDK should raise the exception with headers if the status id is not returned.

**Comment by yaxia** [comment] 2016-11-30 04:54
We don't see anything abnormal at the server side. I will close this issue. Feel free to reopen it if you meet it again.

**Closed** 2016-12-01 03:12 UTC
