### ISSUE TITLE
<Faraday::ConnectionFailed wrapped=#<Net::OpenTimeout: execution expired>

### ISSUE THREAD

**Issue by gossion** [Azure/azure-storage-ruby#118] opened 2018-03-09 03:46 UTC
We saw such error twice in last several months in Cloud Foundry test runners. One time it timed out to insert entity to table of storage account, one time it timed out to update a vhd footer.

Here is error for the later one:
```
D, [2018-03-08T14:45:07.411593 #35913] DEBUG -- [req_id cpi-884469]: check_completion - checking the status of the asynchronous operation using `'
I, [2018-03-08T14:45:07.412732 #35913]  INFO -- [req_id cpi-884469]: create_empty_vhd_blob: Start to generate vhd footer
I, [2018-03-08T14:45:07.415605 #35913]  INFO -- [req_id cpi-884469]: create_empty_vhd_blob: Calling create_page_blob(bosh, bosh-data-8e3857d9-8d12-46c4-be48-993a9a98c14e.vhd, 4294967808, {:timeout=>120, :request_id=>"9932d1da-c7b9-401f-9f88-7f9b10e60fc0"})
I, [2018-03-08T14:45:07.465575 #35913]  INFO -- [req_id cpi-884469]: create_empty_vhd_blob: Start to upload vhd footer
I, [2018-03-08T14:45:07.465752 #35913]  INFO -- [req_id cpi-884469]: create_empty_vhd_blob: Calling put_blob_pages(bosh, bosh-data-8e3857d9-8d12-46c4-be48-993a9a98c14e.vhd, 4294967296, 4294967807, [VHD-FOOTER], {:timeout=>120, :request_id=>"2f141f9a-f438-40a2-98fd-3b2be9773655"})
I, [2018-03-08T14:46:17.495085 #35913]  INFO -- [req_id cpi-884469]: create_empty_vhd_blob: Calling delete_blob(bosh, bosh-data-8e3857d9-8d12-46c4-be48-993a9a98c14e.vhd, {:request_id=>"9e88d555-8c3a-462a-b54f-85b392f04315"})
E, [2018-03-08T14:46:17.526731 #35913] ERROR -- [req_id cpi-884469]: create_empty_vhd_blob: Failed to create empty vhd blob: #<Faraday::ConnectionFailed wrapped=#<Net::OpenTimeout: execution expired>>
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/resolv-replace.rb:25:in `initialize'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/resolv-replace.rb:25:in `initialize'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:904:in `open'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:904:in `block in connect'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
```

Source code for this error is https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/v35.1.0/src/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb#L117-L134
By looking into the code, the vhd blob was created successfully. But when it tried to update vhd footer it got a time out error (last for 70 seconds).

The error is not reproduced firmly. Can you advise us on how to avoid the error?

**Comment by yaxia** [comment] 2018-03-09 04:50
@gossion would you please share your account name that met the timeout issue?

**Comment by gossion** [comment] 2018-03-09 04:53
Thanks @yaxia for quick response.

The storage account is `dsew7o374m6wucfdefaultsa` in resource group ICA-RG-UNManagedCF-3-8-5-19-10 in subscription 4be8920b-2978-43d7-ab14-04d8549c1d05: /subscriptions/4be8920b-2978-43d7-ab14-04d8549c1d05/resourceGroups/ICA-RG-UNManagedCF-3-8-5-19-10/providers/Microsoft.Storage/storageAccounts/dsew7o374m6wucfdefaultsa
Timestamp is 2018-03-08T14:45:07.465752 (UTC)

**Comment by yaxia** [comment] 2018-03-09 05:24
The server log shows the request was successfully processed in 9ms. It looks the response was lost in the client side. So you can see the timeout was not from the server response, it was `Net::OpenTimeout` which uses [60 seconds](http://ruby-doc.org/stdlib-2.3.1/libdoc/net/http/rdoc/Net/HTTP.html#method-i-read_timeout-3D) as the default. 

This is supposed to be handled by the retry policy. Do you use a retry policy that will retry the request on this local error?

**Comment by gossion** [comment] 2018-03-09 05:33
We have a retry policy at https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/v35.1.0/src/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb#L471-L498, however, `Net::OpenTimeout` is not in the retry list.
Do you have recommendation which errors should be retried?

**Comment by yaxia** [comment] 2018-03-09 05:56
If you inherit the retry policy from `Azure::Storage::Core::Filter::ExponentialRetryPolicyFilter`, this [code](https://github.com/Azure/azure-storage-ruby/blob/master/common/lib/azure/storage/common/core/filter/retry_filter.rb#L114-L115) should do the retry for timeout. Let me take a further look why it didn't trigger the retry.

**Comment by yaxia** [comment] 2018-03-12 02:39
@gossion I double checked the code with `#<Faraday::ConnectionFailed wrapped=#<Net::OpenTimeout: execution expired>>` in the error message, it reached to the expected retry policy. So I suspect the error was thrown after retries. Can you increase the retry count (`CustomizedRetryPolicyFilter.new retry_count`) and add log in the `CustomizedRetryPolicyFilter` to make sure it is called?

**Comment by gossion** [comment] 2018-03-12 03:35
add traceback:
```
E, [2018-03-08T14:46:17.526731 #35913] ERROR -- [req_id cpi-884469]: create_empty_vhd_blob: Failed to create empty vhd blob: #<Faraday::ConnectionFailed wrapped=#<Net::OpenTimeout: execution expired>>
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/resolv-replace.rb:25:in `initialize'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/resolv-replace.rb:25:in `initialize'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:904:in `open'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:904:in `block in connect'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:876:in `start'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:33:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/http_response_helper.rb:27:in `set_up_response'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/http_request.rb:143:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/retry_policy.rb:41:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/retry_policy.rb:41:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/signer_filter.rb:28:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/signer_filter.rb:28:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/service.rb:36:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/filtered_service.rb:34:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/signed_service.rb:41:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-storage-0.12.3.preview/lib/azure/storage/service/storage_service.rb:53:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-storage-0.12.3.preview/lib/azure/storage/blob/blob_service.rb:59:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-storage-0.12.3.preview/lib/azure/storage/blob/page.rb:173:in `put_blob_pages'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:126:in `block in create_empty_vhd_blob'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:414:in `block in initialize_blob_client'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:403:in `synchronize'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:403:in `initialize_blob_client'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:99:in `create_empty_vhd_blob'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/disk_manager.rb:65:in `create_disk'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:385:in `block in create_disk'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:348:in `create_disk'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:39:in `<top (required)>'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r3/bin/bundle:30:in `block in <main>'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r3/bin/bundle:22:in `<main>'

```

**Comment by yaxia** [comment] 2018-03-12 03:36
Thanks for the updated call stack. According to it, it was using azure-core 0.1.12 which had a [issue](https://github.com/Azure/azure-ruby-asm-core/issues/51) in retry. Please update azure-core to the latest to have the fix. So closing it now.

**Comment by gossion** [comment] 2018-03-12 03:37
thanks @yaxia very much.

**Closed** 2018-03-12 03:38 UTC
Labels: help wanted

**Comment by bingosummer** [comment] 2018-03-13 03:46
@yaxia 
According to https://github.com/fog/fog-azure-rm/issues/357#issuecomment-351343521, azure-core 0.1.13 has the bug of retry policy, but 0.1.12 doesn’t.
With 0.1.13, fog-azure-rm re-throws the error. With 0.1.12, fog-azure-rm doesn't.

So, could you please confirm whether 0.1.12 also has the issue in retry? If yes, we can update azure-core to the latest (0.1.14) to fix it. If not, then the bug of retry policy may not be the root cause of this issue.

**Comment by yaxia** [comment] 2018-03-13 04:54
@bingosummer The bug you mentioned in azure-core 0.1.13 was caused by a different reason where the class member stored the previous error, though it also residented in the retry policy. This issue was caused by the local variable in the method that didn't clean the previous error. The fix in 0.1.14 fixed both cases.
