### ISSUE TITLE
azure-storage can't work with rspec 3.2.0+

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-storage-ruby#87] opened 2017-05-27 07:31 UTC
https://github.com/rspec/rspec-mocks/issues/1161

Could you please confirm the bug in `azure-storage` which is described in the above issue?

**Comment by yaxia** [comment] 2017-06-05 06:54
@bingosummer The error message you saw was caused by missing parameter in initializing the `Azure::Storage::Client` class, which requires storage account access information be set either in the environment or in the `options` argument.

I don't know how exactly `allow(client).to receive(:storage_table_host=)` work in rspec. Could you please share more on how are those storage account information set in your project? Why the [commit](https://github.com/rspec/rspec-support/issues/317) worked around the issue?

**Comment by yaxia** [comment] 2017-06-06 05:30
This issue is caused by the Azure::Storage::client is used in `method_missing`. I will fix it in next release, please stay tuned. Thanks.

**Comment by bingosummer** [comment] 2017-09-25 02:51
Hi @yaxia, how is this issue going?

**Comment by yaxia** [comment] 2017-09-25 02:52
@katmsft is working on it and will have the fix in the upcoming release. Thanks.

**Comment by katmsft** [comment] 2017-09-28 08:28
Fixed in 0.14.0. @bingosummer check it out!

**Closed** 2017-11-17 17:16 UTC
