### ISSUE TITLE
Fails to insert records to storage account table

### ISSUE THREAD

**Issue by gossion** [Azure/azure-storage-ruby#48] opened 2016-09-05 07:58 UTC
I got an error when insert a record to storage account table randomly. Sometime it can be reproduced, sometime not.

Error log:

```
   Failed creating missing vms > etcd_z1/0 (e4f6733c-7c66-4f3a-8781-1e716ac3e117): insert_entity: #<RuntimeError: Xml is not a entry node.>
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/azure-storage-0.10.2.preview/lib/azure/storage/service/serialization.rb:297:in `expect_node'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/azure-storage-0.10.2.preview/lib/azure/storage/table/serialization.rb:102:in `hash_from_entry_xml'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/azure-storage-0.10.2.preview/lib/azure/storage/table/table_service.rb:220:in `insert_entity'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/table_manager.rb:54:in `insert_entity'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/stemcell_manager.rb:114:in `handle_stemcell_in_different_storage_account'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/stemcell_manager.rb:70:in `has_stemcell?'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:107:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_common-1.3262.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:104:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>' (00:00:25)
```

**Comment by gossion** [comment] 2016-09-05 08:02
By checking code from https://github.com/Azure/azure-storage-ruby/blob/master/lib/azure/storage/table/table_service.rb#L212-L228 and documents from http://msdn.microsoft.com/en-us/library/azure/dd179433, it looks like response body can have different formats (and it is said that 'JSON is the recommended payload format, and is the only format supported for versions 2015-12-11 and later'), but function insert_entity() expect the response body to be xml.
```ruby

      def insert_entity(table_name, entity_values, options={})
        ...
        response = call(:post, entities_uri(table_name, nil, nil, query), body)

        result = Table::Serialization.hash_from_entry_xml(response.body)
        ...
      end
```
Is it the reason why it fails sometime?

**Comment by yaxia** [comment] 2016-09-07 08:49
The azure-storage gem 0.11.0.preview is still targeting on the API version 2015-04-05 which still supports XML payload. 

The failure may caused by several reasons:
1. The body is somehow not in the XML format.
2. The `insert-entity` doesn't enforce `application/atom+xml` in the `accept` header.

I will investigate.

**Comment by gossion** [comment] 2016-09-07 08:58
Thanks. 

For your investigation: we saw the error on gem 0.10.2.preview. But we will switch to 0.11.0.preview soon, since the error only happen randomly I am not sure if we can reproduce it on 0.11. Anyway, will let you know if we see the error again.

**Comment by yaxia** [comment] 2016-10-31 03:22
We will close it for now. If you see it again, feel free to reopen the issue. Thanks.

**Closed** 2016-10-31 06:45 UTC
